name: ai-hub

on:
  push:
    branches: [ main-legacy ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_HOST }}
        password: ${{ secrets.SSH_VPS_PASSWORD }}
        script: |
          cd /opt/apps/chat
          nohup /opt/apps/chat/chat-server/src/scripts/restart-app.sh &> server.log &!
          sleep 20
